version: '3.1'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: bind
        source: "./conf.d"
        target: "/etc/mysql/conf.d"
      - type: bind
        source: "./docker-entrypoint-initdb.d"
        target: "/docker-entrypoint-initdb.d"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
